from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from dotenv import load_dotenv
import os

load_dotenv()

client = WebClient(token=os.getenv("SLACK_BOT_TOKEN"))
CHANNEL_ID = os.getenv("SLACK_CHANNEL_ID")

def post_to_slack(messages: dict, tone: str, severity: str):
    """
    Post generated outage messages to Slack channel.
    
    Args:
        messages: dict with initial, in_progress, resolved keys
        tone: tone used for generation
        severity: detected severity level
    """
    try:
        severity_emoji = {
            "low": "🟡",
            "medium": "🟠", 
            "high": "🔴"
        }.get(severity.lower(), "⚪")

        slack_message = f"""
{severity_emoji} *New Outage Communication Generated*
*Severity:* {severity.upper()} | *Tone:* {tone.capitalize()}

📢 *INITIAL ALERT:*
{messages.get('initial', 'N/A')}

🔄 *IN-PROGRESS UPDATE:*
{messages.get('in_progress', 'N/A')}

✅ *RESOLVED NOTICE:*
{messages.get('resolved', 'N/A')}

_Generated by OutageComms AI — Infinite Computer Solutions 2026_
        """

        response = client.chat_postMessage(
            channel=CHANNEL_ID,
            text=slack_message,
            mrkdwn=True
        )

        if response["ok"]:
            print("✅ Successfully posted to Slack!")
            return True
        else:
            print("❌ Failed to post to Slack")
            return False

    except SlackApiError as e:
        print(f"Slack API Error: {e.response['error']}")
        return False
    except Exception as e:
        print(f"Error: {e}")
        return False

def test_slack_connection():
    """Test if Slack connection works"""
    try:
        response = client.auth_test()
        print(f"✅ Connected as: {response['bot_id']}")
        return True
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        return False

if __name__ == "__main__":
    print("Testing Slack connection...")
    test_slack_connection()
    
    print("\nPosting test message...")
    test_messages = {
        "initial": "We are aware some customers are experiencing issues. Our team is investigating.",
        "in_progress": "Our team is actively working to resolve the issue. Thank you for your patience.",
        "resolved": "The issue has been fully resolved. All services are back to normal."
    }
    post_to_slack(test_messages, "empathetic", "medium")
